services:
  main-site:
    build: . # Sagt Docker: Nutze das Dockerfile im selben Ordner
    container_name: main-site
    restart: always
    networks:
      - traefik_proxy
    # VOLUMES FÜR DEN CODE KOMMEN RAUS!
    # Nur die nginx.conf bleibt, falls du eine spezielle hast.
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-site.rule=Host(`elyesghazel.ch`) || Host(`www.elyesghazel.ch`)"
      - "traefik.http.routers.main-site.entrypoints=https"
      - "traefik.http.routers.main-site.tls=true"
      - "traefik.http.routers.main-site.tls.certresolver=cloudflare"
      - "traefik.http.services.main-site.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
