name: Deployment Swisscom Portfolio
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: docker # Runner in Docker Container
    steps:
      - name: Deploy via SSH
        uses: https://github.com/appleboy/ssh-action@master
        with:
          host: 159.195.34.0
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /opt/docker/websites/swisscom/react-portfolio/
            # no git crying
            git config --global --add safe.directory /opt/docker/websites/swisscom/react-portfolio/
            git pull origin main
            # force rebuild
            docker compose build --no-cache
            docker compose up -d
